### ISSUE TITLE
Add Twitter/Instagram/LinkedIn icons to footer

### ISSUE THREAD

**Issue by LEQUI000** [CurtisGreen/dallas-area-transit-alliance#20]
Add a footer to follow the new established social media channels and build the accounts

**Comment by LEQUI000** [comment]
P3

**Comment by LEQUI000** [comment]
Footer also should be added with a statement that this organization is not funded or affiliated with DART.

**Comment by LEQUI000** [comment]
Sample wording for now.

> Dallas Area Transit Alliance (DATA) is a rider-run advocacy group that is not affiliated with Dallas Area Rapid Transit, or any other transit or government agency.

**Comment by cullam3n** [comment]
Dallas Area Transit Alliance (DATA) is a rider-run advocacy group that is
not affiliated with Dallas Area Rapid Transit, or any other transit or
government agency.

That is a little more succinct.

**Comment by Schobbish** [comment]
As a part of this can we move all the icons to their own folder too lol

**Comment by LEQUI000** [comment]
I think that's a good idea for any external svg logos to move into their own folder
