### ISSUE TITLE
Show cover in social media share

### ISSUE THREAD

**Issue by LEQUI000** [CurtisGreen/dallas-area-transit-alliance#28]
When sharing a social media post the metadata should return the cover image.

Currently the image shows blank which can impact user experience.

![image](https://github.com/user-attachments/assets/a846bd31-ee99-4cd8-99ec-108a9737fdd5)

**Comment by CurtisGreen** [comment]
Addressed in https://github.com/CurtisGreen/dallas-area-transit-alliance/pull/30
